Updating package.json due to failed Heroku node app build
First `git push heroku master` failed with the following error:

```
remote: -----> Node.js app detected
remote: parse error: Expected another key-value pair at line 11, column 3
remote:  !     Unable to parse package.json
remote:
remote:
remote: -----> Build failed
remote: parse error: Expected another key-value pair at line 11, column 3
remote: parse error: Expected another key-value pair at line 11, column 3
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to trollbusters-bot.
remote:
To https://git.heroku.com/trollbusters-bot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/trollbusters-bot.git'
```
Made changes to package.json in order to try again.

Responds to issue #1.